### ISSUE TITLE
Support for collection prefix

### ISSUE THREAD

**Issue by claudiuconstantin** [DataMicron/quartznet-mongodb#11]
Does quartznet-mongodb provide support for setting the collection prefix when creating the necessary collections in Mongo?

**Comment by mxurshid** [comment]
If you want to use the same mongo database for all quarz projects, you can configure quartz config as follows:
```
<quartz>
     ...
     <add key="quartz.jobStore.tablePrefix" value="qrtz1." />
     ...
</quartz>
```
```
<quartz>
     ...
     <add key="quartz.jobStore.tablePrefix" value="qrtz2." />
     ...
</quartz>
```

**Comment by claudiuconstantin** [comment]
Alright, I correctly tested it now and it works. Thank you!
