### ISSUE TITLE
Update Quartz.MongoDB nuget package

### ISSUE THREAD

**Issue by claudiuconstantin** [DataMicron/quartznet-mongodb#8]
Would it be a good idea to also update the Quartz.MongoDB nuget [package](https://www.nuget.org/packages/Quartz.MongoDB/) with the latest code? Is there a way I can help with that?

**Comment by mxurshid** [comment]
Thanks! Just updated nuget [package](https://www.nuget.org/packages/Quartz.MongoDB/0.1.5)

**Comment by claudiuconstantin** [comment]
Got it, tested it, works :) Thanks!
